### PR TITLE
Minor changes to pass CRAN checks (ready to reupload to CRAN)

### PR DESCRIPTION
**Pull request by garthtarr**
Currently rpivotTable can't be installed from CRAN using `install.packages()`:

https://cran.r-project.org/web/packages/rpivotTable/index.html

Package ‘rpivotTable’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2016-05-02 as check problems were not corrected despite reminders.

This PR is an attempt to pass CRAN checks (and minor changes to testthat testing).

### CODE REVIEW

**Comment by timelyportfolio** [comment]
thanks @garthtarr.  I did not know this.  @smartinsightsfromdata, need any help restoring this on CRAN?

**Comment by timelyportfolio** [comment]
@smartinsightsfromdata, any interest in maintaining?  If not, I'll fork and submit to CRAN under a different name.  I'd really like to keep it under you though with a consistent name.

**Comment by smartinsightsfromdata** [comment]
I will resubmit this weekend.  Many thanks for prompting me.

**Comment by smartinsightsfromdata** [comment]
It is back on CRAN.  

@garthtarr  @timelyportfolio 

I've added Kenton and Garth as contributors.  Thanks

**Pull request merged**
