### PR TITLE
Support for the sorters parameter

### PR DESCRIPTION
**Pull request by palatinuse**
I wanted to pass to rpivotTable the sorters parameter to define my own sorting function on a column, but rpivotTable crashes with an error message.
With this modification this attribute get's correctly passed on to pivottable.js

### CODE REVIEW

**Comment by smartinsightsfromdata** [comment]
@palatinuse Thanks for this!

**Comment by smartinsightsfromdata** [comment]
@palatinuse Actually, could you kindly provide an example?

**Comment by palatinuse** [comment]
Here is the way I specify a sorter for some columns:

rpivotTable(myDataFrame, 
              rows = c("machine"), 
              cols = c("columnA", "columnB"),
              rendererName = "Table Barchart",
              aggregatorName="List Unique Values", vals="columnC",
              sorters = "
function(attr) { 
  var sortAs = $.pivotUtilities.sortAs;
  if (attr == \"machine\") { 
    return sortAs([\"Core\", \"Penryn\", \"Nehalem\", \"Westmere\", \"Sandy Bridge\", \"Ivy Bridge\"]);
  } else if (attr == \"columnA\" || attr == \"columnB\") {
    return sortAs([\"light\", \"medium\", \"heavy\"])
  }
}")

**Comment by smartinsightsfromdata** [comment]
Great. Incidentally, I wonder if you would be willing to help on another feature of pivottable.

Users have requested to be able to get back the parameters used for slicing and dicing.  Nicolas has an [example here ](http://nicolas.kruchten.com/pivottable/examples/onrefresh.html). As I'm not exactly a JS hacker, it would take me a lot of time to get it right.  
Would you be interested in helping?

**Comment by palatinuse** [comment]
I am unfortunately also not a JS expert, so I cannot help with that.

**Comment by smartinsightsfromdata** [comment]
No worries.  It is sorted now

**Pull request merged**
