### PR TITLE
Subtotals

### PR DESCRIPTION
**Pull request by timelyportfolio**
#74 

* Library updated to 2.13.0 version of pivottable (see [2.12.0](https://github.com/nicolaskruchten/pivottable/releases/tag/v2.12.0) for new functionality)
* Add subtotal renderer [pivottable-subtotal-renderer](https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer)

### CODE REVIEW

**Comment by timelyportfolio** [comment]
@smartinsightsfromdata any thoughts on this?  I am sure you are busy, but I would really appreciate an update.  Thanks.

**Comment by timelyportfolio** [comment]
@smartinsightsfromdata, you there?  I think this is very helpful and useful functionality and does not change the core api.

**Comment by smartinsightsfromdata** [comment]
@nicolaskruchten Please advise. Thanks

**Comment by nicolaskruchten** [comment]
@smartinsightsfromdata @timelyportfolio I'll try to get this merged in, along with an update to the very latest pivottable.js this week :)

**Comment by nicolaskruchten** [comment]
@timelyportfolio I used this PR to build #88 and the PivotTable.js version was updated in #87 so I think it makes sense to close this PR now if that's OK with you?

**Comment by timelyportfolio** [comment]
Thanks @nicolaskruchten!!

**Pull request closed without merging**
