### PR TITLE
comprehensive rewrite

### PR DESCRIPTION
**Pull request by timelyportfolio**
This pull is a pretty comprehensive rewrite to fix/improve (in my opinion of course) the initially drafted `htmlwidget`.  I'll try to highlight the changes below.

1.  Remove all excess dependencies
1.  Remove all unnecessary and environment files
2.  Bump `jquery` and `jqueryui` to their newest versions
1.  Document all the parameters to the `rpivotTable` function
1.  Add examples for most of the parameters
1.  Support parameters in the Javascript binding

Would love to know @jcizel and @smartinsightsfromdata thoughts.  Thanks guys.

### CODE REVIEW

**Comment by timelyportfolio** [comment]
I just saw where this will not be automatically merged.  I can try to rebase from @smartinsightsfromdata `master` so that it will merge more cleanly.

**Comment by smartinsightsfromdata** [comment]
@timelyportfolio I'm fine to merge if you could rebase to the latest master.  Thanks

**Comment by jcizel** [comment]
@timelyportfolio and @smartinsightsfromdata, thanks for the great work, and sorry for the late reply. I’ve tried out the latest version submitted by @timelyportfolio and it works well. I’m planning to spend some more time this weekend on enabling the Treemap renderer. So far I didn’t have much success with that, since the resulting plot would at most consist of rectangles stacked in a vertical sequence. Let me know if you have any ideas on how to make this work.

**Comment by smartinsightsfromdata** [comment]
@jcizel & @timelyportfolio I got the same result - no matter what I did.  I've used jsfiddle to be in a clean environment but still with no luck on treemap.  See [here](http://jsfiddle.net/Enzoma/qm7wxuy0/2/)
Any suggestion is welcome.

**Comment by smartinsightsfromdata** [comment]
@jcizel  @timelyportfolio It works!!
See this [jsfiddle](http://jsfiddle.net/Enzoma/qm7wxuy0/4/)
It is a "simple" css issue. As I like most of the changes made by @jcizel it would make sense to add the style sheet to that branch.

**Comment by timelyportfolio** [comment]
Think that the only necessary bit of this CSS is the `position: absolute;`.  I'll try it out.  I can add in yaml as another style dependency or potentially modify the renderer.  However, I generally try to avoid hacking the source javascript library,so I think the yaml solution will be better.

**Comment by timelyportfolio** [comment]
the d3 renderers are back.  Please test.  Thanks everyone.

**Comment by smartinsightsfromdata** [comment]
@timelyportfolio  @jcizel FYI: I just committed few css changes for Treemap. Smaller fonts (important especially with busy Treemaps) and clearer borders between tiles.

**Comment by jcizel** [comment]
@smartinsightsfromdata, @timelyportfolio, this is great! Treemaps now work like a charm. Thanks for all the work!

**Pull request merged**
