### PR TITLE
update to 2.19.0, fix locales

### PR DESCRIPTION
**Pull request by nicolaskruchten**
Here at last is my first PR to update PivotTable.js to the latest version (2.19.0) and to fix the `change_locale` function which isn't working for me, and has been reported in #73 

I don't suggest merging it immediately, as some changes to the documentation are warranted, and I may be able to do another PivotTable release this week, but any feedback would be welcome!

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
I should add that this PR would address #85 and #83 as well.

**Comment by smartinsightsfromdata** [comment]
@nicolaskruchten Changes seem straightforward, thanks. Should be able to do some testing by the weekend.  But ideally I would like to merge this PR asap, as well as Kent's one (assuming you are OK with it).

In any case, if you think you'll submit another PR soon, it is worth wait for that before submit to CRAN.

Let me know if this plan suits you.

**Comment by nicolaskruchten** [comment]
I'd prefer to wait a bit, as I would want to think about how this would impact people with existing code... I think this PR is good to go now, if you want to merge it and start the CRAN process :)

**Comment by nicolaskruchten** [comment]
I should add that this PR doesn't include the subtotals plugin. If we can merge this PR in, I can take a look at adapting #75 for inclusion on top of this one. I would be fine with doing a CRAN release just as-is though.

**Comment by smartinsightsfromdata** [comment]
@nicolaskruchten  Merged, but as you've already noticed there are now (minor) conflicts. 
I'm fine to submit it to CRAN as soon as the subtotals are in. We can then breathe and wait a bit for the next one...

**Comment by nicolaskruchten** [comment]
OK, what minor conflicts are there?

**Comment by nicolaskruchten** [comment]
Oh you mean with subtotals. Yeah I know, I'll just get another PR set up instead of trying to resolve the conflicts.

**Pull request merged**
